### ISSUE TITLE
Provide a precompiled windows binary

### ISSUE THREAD

**Issue by vrillusions** [dokan-dev/dokan-sshfs#8]
In the same way dokany has a windows binary available, could you provide a binary for dokan-sshfs as well?  Thanks for all your work.

**Comment by Liryna** [comment]
Hi @vrillusions ,

See https://github.com/dokan-dev/dokan-sshfs/issues/5

But I think we are going to begin to do it with all this request :smile: 

The problem is also that we are already only two for dokany and it already take a lots of time.
Dokan-sshfs need contributor to be alive !

If some people are motivated to update dokan-sshfs, I would be happy to make a installer and update it !

**Comment by Liryna** [comment]
We should do it as appveyor build artefact.

**Comment by wyatt8740** [comment]
I'd be equally satisfied with a simple makefile so I can build it from MinGW, too. VS is not part of my workflow.

**Comment by Liryna** [comment]
Appveyor build and download link has been added to readme 👍 https://github.com/dokan-dev/dokan-sshfs/blob/master/README.md#download

A new release will be build at each commit

**Comment by ststeiger** [comment]
There are no binaries in Appveyor build, they are deleted after 3 months.

**Comment by Liryna** [comment]
There is a new one now https://ci.appveyor.com/project/Liryna/dokan-sshfs/build/artifacts
